version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: baa
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "baa"]
      interval: 5s
      retries: 5
    restart: always